In [9]:
import pandas as pd

adres = "/workspace/pythonfundamentals/Egzersizler/pehlivan/data/pokemon.csv"
df = pd.read_csv(adres)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,791,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,792,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,793,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,794,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,795,Zygarde Half Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.head(5)

In [ ]:
df.describe()

In [ ]:
df.tail(10)